/**
 * PokeIQ Raid Engine
 * ------------------
 * Pokémon GO PvE energy calculations.
 *
 * This module handles:
 * - energy storage
 * - Fast Move energy generation
 * - Charged Move energy costs
 * - the 100-energy cap
 * - energy gained from taking damage
 *
 * It does NOT decide when moves are used or when
 * incoming raid-boss damage occurs. Those belong
 * to the battle/moveset simulator.
 */

export const MAX_ENERGY = 100

export const DAMAGE_ENERGY_PER_HP = 0.5

// --------------------------------------------------
// Validation
// --------------------------------------------------

function requireFiniteNumber(
  value,
  label
) {
  if (!Number.isFinite(value)) {
    throw new Error(
      `${label} must be a finite number.`
    )
  }

  return value
}

function requireEnergy(energy) {
  requireFiniteNumber(
    energy,
    'energy'
  )

  if (
    energy < 0 ||
    energy > MAX_ENERGY
  ) {
    throw new Error(
      `energy must be between 0 and ${MAX_ENERGY}.`
    )
  }

  return energy
}

// --------------------------------------------------
// Move energy values
// --------------------------------------------------

/**
 * Fast Moves use positive energyDelta values.
 */
export function getFastMoveEnergy(
  energyDelta
) {
  requireFiniteNumber(
    energyDelta,
    'energyDelta'
  )

  if (energyDelta < 0) {
    throw new Error(
      'Fast Move energyDelta cannot be negative.'
    )
  }

  return energyDelta
}

/**
 * Charged Moves are represented in the Game Master
 * with negative energyDelta values.
 *
 * Example:
 *
 * Outrage
 * energyDelta = -50
 *
 * Energy cost = 50
 */
export function getChargedMoveCost(
  energyDelta
) {
  requireFiniteNumber(
    energyDelta,
    'energyDelta'
  )

  if (energyDelta > 0) {
    throw new Error(
      'Charged Move energyDelta cannot be positive.'
    )
  }

  return Math.abs(
    energyDelta
  )
}

// --------------------------------------------------
// Energy storage
// --------------------------------------------------

/**
 * Adds energy while respecting the 100-energy cap.
 *
 * Any excess energy is discarded.
 *
 * Example:
 *
 * 96 + 8 = 100
 *
 * not 104.
 */
export function addEnergy(
  currentEnergy,
  amount
) {
  requireEnergy(
    currentEnergy
  )

  requireFiniteNumber(
    amount,
    'amount'
  )

  if (amount < 0) {
    throw new Error(
      'amount cannot be negative.'
    )
  }

  return Math.min(
    currentEnergy + amount,
    MAX_ENERGY
  )
}

/**
 * Returns whether the Pokémon currently has enough
 * energy to use a Charged Move.
 */
export function canUseChargedMove(
  currentEnergy,
  energyCost
) {
  requireEnergy(
    currentEnergy
  )

  requireFiniteNumber(
    energyCost,
    'energyCost'
  )

  if (energyCost < 0) {
    throw new Error(
      'energyCost cannot be negative.'
    )
  }

  return (
    currentEnergy >=
    energyCost
  )
}

/**
 * Spends energy on a Charged Move.
 *
 * Throws if the Pokémon cannot afford the move.
 */
export function spendEnergy(
  currentEnergy,
  energyCost
) {
  requireEnergy(
    currentEnergy
  )

  requireFiniteNumber(
    energyCost,
    'energyCost'
  )

  if (energyCost < 0) {
    throw new Error(
      'energyCost cannot be negative.'
    )
  }

  if (
    !canUseChargedMove(
      currentEnergy,
      energyCost
    )
  ) {
    throw new Error(
      `Not enough energy. Have ${currentEnergy}, need ${energyCost}.`
    )
  }

  return (
    currentEnergy -
    energyCost
  )
}

// --------------------------------------------------
// Move application
// --------------------------------------------------

/**
 * Applies the energy generated by a Fast Move.
 */
export function applyFastMoveEnergy(
  currentEnergy,
  energyDelta
) {
  const energyGain =
    getFastMoveEnergy(
      energyDelta
    )

  return addEnergy(
    currentEnergy,
    energyGain
  )
}

/**
 * Applies the energy cost of a Charged Move.
 */
export function applyChargedMoveEnergy(
  currentEnergy,
  energyDelta
) {
  const energyCost =
    getChargedMoveCost(
      energyDelta
    )

  return spendEnergy(
    currentEnergy,
    energyCost
  )
}

// --------------------------------------------------
// Damage-generated energy
// --------------------------------------------------

/**
 * Calculates energy generated from HP lost.
 *
 * Gym/Raid Pokémon gain 0.5 energy per HP lost.
 *
 * This function does not apply the 100-energy cap,
 * because it only calculates the amount generated.
 */
export function calculateDamageEnergy(
  hpLost
) {
  requireFiniteNumber(
    hpLost,
    'hpLost'
  )

  if (hpLost < 0) {
    throw new Error(
      'hpLost cannot be negative.'
    )
  }

  return (
    hpLost *
    DAMAGE_ENERGY_PER_HP
  )
}

/**
 * Applies energy generated from incoming damage
 * while respecting the normal 100-energy cap.
 */
export function applyDamageEnergy(
  currentEnergy,
  hpLost
) {
  const energyGain =
    calculateDamageEnergy(
      hpLost
    )

  return addEnergy(
    currentEnergy,
    energyGain
  )
}