import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

const SPECIES_LIST_URL =
  'https://pokeapi.co/api/v2/pokemon-species?limit=100000&offset=0'

const OUTPUT_PATH = path.resolve(
  process.cwd(),
  'src/data/pokemonSpecies.js'
)

const CONCURRENCY = 12
const MAX_RETRIES = 3

function extractIdFromUrl(url) {
  const match = url.match(/\/(\d+)\/?$/)

  return match ? Number(match[1]) : null
}

async function fetchJson(url, attempt = 1) {
  const response = await fetch(url, {
    headers: {
      Accept: 'application/json',
    },
  })

  if (!response.ok) {
    if (attempt < MAX_RETRIES) {
      await new Promise((resolve) =>
        setTimeout(resolve, 500 * attempt)
      )

      return fetchJson(url, attempt + 1)
    }

    throw new Error(
      `Request failed (${response.status}) for ${url}`
    )
  }

  return response.json()
}

function getEnglishName(speciesData) {
  const englishName = speciesData.names?.find(
    (entry) => entry.language?.name === 'en'
  )

  return englishName?.name ?? speciesData.name
}

async function mapWithConcurrency(
  items,
  mapper,
  concurrency
) {
  const results = new Array(items.length)
  let nextIndex = 0

  async function worker() {
    while (true) {
      const currentIndex = nextIndex
      nextIndex += 1

      if (currentIndex >= items.length) {
        return
      }

      results[currentIndex] = await mapper(
        items[currentIndex],
        currentIndex
      )
    }
  }

  await Promise.all(
    Array.from(
      {
        length: Math.min(
          concurrency,
          items.length
        ),
      },
      () => worker()
    )
  )

  return results
}

function buildOutputFile(species) {
  const generatedAt = new Date().toISOString()

  return `/*
  AUTO-GENERATED FILE — DO NOT EDIT BY HAND.

  Generated by:
    node scripts/updatePokemonSpecies.mjs

  Source:
    PokéAPI pokemon-species endpoint

  Generated:
    ${generatedAt}
*/

export const pokemonSpecies = ${JSON.stringify(
    species,
    null,
    2
  )}
`
}

async function main() {
  console.log('Fetching Pokémon species list...')

  const listData = await fetchJson(
    SPECIES_LIST_URL
  )

  const baseSpecies = listData.results
    .map((entry) => ({
      id: extractIdFromUrl(entry.url),
      apiName: entry.name,
      url: entry.url,
    }))
    .filter((entry) =>
      Number.isInteger(entry.id)
    )
    .sort(
      (speciesA, speciesB) =>
        speciesA.id - speciesB.id
    )

  console.log(
    `Found ${baseSpecies.length} species. Fetching English names...`
  )

  let completed = 0

  const species = await mapWithConcurrency(
    baseSpecies,
    async (entry) => {
      const speciesData = await fetchJson(
        entry.url
      )

      completed += 1

      if (
        completed % 50 === 0 ||
        completed === baseSpecies.length
      ) {
        console.log(
          `Loaded ${completed}/${baseSpecies.length} species`
        )
      }

      return {
        id: entry.id,
        name: getEnglishName(speciesData),
        apiName: entry.apiName,
      }
    },
    CONCURRENCY
  )

  await mkdir(
    path.dirname(OUTPUT_PATH),
    {
      recursive: true,
    }
  )

  await writeFile(
    OUTPUT_PATH,
    buildOutputFile(species),
    'utf8'
  )

  console.log('')
  console.log(
    `Wrote ${species.length} species to:`
  )
  console.log(OUTPUT_PATH)
}

main().catch((error) => {
  console.error('')
  console.error('Species update failed:')
  console.error(error)

  process.exitCode = 1
})